language: python

matrix:
  include:
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

services:
    - docker

install:
    - pip install flake8
    - docker build . -t baselines-test

script:
    - flake8 . --show-source --statistics
    - docker run baselines-test pytest -v .
